# This is the BannerBoard configuration
# Make sure to always make a backup of this file before making any changes!
# Made by BigTeddy98

# Every BannerBoard has some internal settings stored in this file.
# Please do not make any changes to whatever is in the internal section.

lastUsedId: 0
